---
slurmweb_enabled: false
slurmweb_bootstrap: false
slurmweb_hostname: "{{ inventory_hostname }}"
slurmweb_http_server_names:
- "{{ slurmweb_hostname }}"
slurmweb_jwt_key: /var/lib/slurm-web/jwt.key
slurmweb_slurmrestd_uri: unix:/run/slurmrestd/slurmrestd.socket
slurmweb_slurmrestd_auth: local
slurmweb_slurmrestd_jwt_mode: auto
slurmweb_slurmrestd_jwt_key: /var/lib/slurm-web/slurmrestd_jwt_hs256.key
slurmweb_slurmrestd_jwt_token: null
slurmweb_local_slurmrestd_jwt_key_file: jwt_hs256.key  # dummy
slurmweb_gateway_subdir: ""
slurmweb_agent_subdir: agent
slurmweb_agent_service_override_path: /etc/systemd/system/slurm-web-agent-uwsgi.service.d/firehpc.conf
slurmweb_agent_settings_defaults: {}
slurmweb_gateway_settings_defaults: {}
slurmweb_agent_settings: {}
slurmweb_gateway_settings: {}
slurmweb_local_ca_dir: ca  # dummy
slurmweb_local_ca_password_file: "{{ slurmweb_local_ca_dir }}/ca.password"
slurmweb_local_ca_key_file: "{{ slurmweb_local_ca_dir }}/key.pem"
slurmweb_local_ca_cert_file: "{{ slurmweb_local_ca_dir }}/ca.crt"
slurmweb_local_tls_key_file: "{{ slurmweb_local_ca_dir }}/key-slurmweb.pem"
slurmweb_local_tls_cert_file: "{{ slurmweb_local_ca_dir }}/cert-slurmweb.crt"

slurmweb_tls_dir: /etc/slurm-web/tls
slurmweb_tls_ca_cert_file: "{{ slurmweb_tls_dir }}/ca.crt"
slurmweb_tls_cert_file: "{{ slurmweb_tls_dir }}/cert.crt"
slurmweb_tls_key_file: "{{ slurmweb_tls_dir }}/key.pem"
